site_name: ויקי פונדקאות לגייז
site_description: ידע קהילתי אנונימי על תהליכי פונדקאות
docs_dir: docs
theme:
  name: material
  language: he
  direction: rtl
  features:
  - navigation.sections
  - navigation.top
  - navigation.indexes
  - search.highlight
  - search.suggest
  - content.code.copy
  palette:
  - scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-night
      name: עבור למצב כהה
  - scheme: slate
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: עבור למצב בהיר
plugins:
- search:
    lang: he
markdown_extensions:
- admonition
- md_in_html
- pymdownx.details
- pymdownx.superfences
- attr_list
- tables
- toc
extra_css:
- stylesheets/hebrew.css
nav:
- בית: index.md
